-- Pipe for album_table
CREATE OR REPLACE PIPE album_table_pipe
    AUTO_INGEST = TRUE
AS
    COPY INTO album_table
    FROM @SNOWFLAKE_ETL_PIPELINE.EXTERNAL_STAGE.SNOWFLAKE_SPOTIFY_STAGE/transformed_data/album_data/
    FILE_FORMAT = (FORMAT_NAME = SNOWFLAKE_ETL_PIPELINE.EXTERNAL_STAGE.CSV_FILE_FORMAT);

-- Pipe for artist_table
CREATE OR REPLACE PIPE artist_table_pipe
    AUTO_INGEST = TRUE
AS
    COPY INTO artist_table
    FROM @SNOWFLAKE_ETL_PIPELINE.EXTERNAL_STAGE.SNOWFLAKE_SPOTIFY_STAGE/transformed_data/artist_data/
    FILE_FORMAT = (FORMAT_NAME = SNOWFLAKE_ETL_PIPELINE.EXTERNAL_STAGE.CSV_FILE_FORMAT);

-- Pipe for song_table
CREATE OR REPLACE PIPE song_table_pipe
    AUTO_INGEST = TRUE
AS
    COPY INTO song_table
    FROM @SNOWFLAKE_ETL_PIPELINE.EXTERNAL_STAGE.SNOWFLAKE_SPOTIFY_STAGE/transformed_data/song_data/
    FILE_FORMAT = (FORMAT_NAME = SNOWFLAKE_ETL_PIPELINE.EXTERNAL_STAGE.CSV_FILE_FORMAT);

-- Select statements
SELECT * FROM album_table;
SELECT * FROM artist_table;
SELECT * FROM song_table;